openapi: 3.0.0
info:
  title: Check AbuseIPDB
  version: 1.0.0
servers:
- url: https://api.abuseipdb.com
paths:
  "/api/v2/check":
    get:
      parameters:
      - name: ip
        in: query
        schema:
          type: string
        required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      summary: This tool checks if an IP address is safe or malicious.
components:
 securitySchemes:
   api_key:
     type: apiKey
     in: header
     name: hibp-api-key
security:
  - api_key: []