openapi: 3.0.0

info:
    title: lesson2-iplookup
    description: Lesson 2 - Basic request to IP lookup API.
    version: "0.2.2"

servers:
    - url: https://wizard-world-api.herokuapp.com/

paths:
    /Houses:
        get:
            operationId: gethouses
            summary: Retrieve all Harry Potter houses
            responses:
                "200":
                    description: Success
