openapi: 3.0.0

info:
    title: lesson2-iplookup
    description: Lesson 2 - Basic request to IP lookup API.
    version: "0.2.0"

servers:
    - url: http://ip-api.com/

paths:
    /json/{ipaddress}:
        get:
            operationId: lookupIpAddressGeolocation
            summary: Lookup IP Address Geolocation information
            parameters:
                - in: path
                  name: ipaddress
                  required: true
            responses:
                "200":
                    description: OK
