openapi: 3.0.0

info:
    title: lesson2-iplookup
    description: Lesson 2 - Basic request to IP lookup API.
    version: "0.2.1"

servers:
    - url: https://api.ip2location.io/

paths:
    /{ip}:
        get:
            operationId: lookupIpAddressGeolocation
            summary: Lookup IP Address Geolocation information
            parameters:
                - in: query
                  name: ip
                  required: true
            responses:
                "200":
                    description: OK
