openapi: 3.0.0

info:
    title: lesson2-iplookup
    description: Lesson 2 - Basic request to IP lookup API.
    version: "0.2.2"

servers:
    - url: https://freeipapi.com/

paths:
    /api/json/{ip}:
        get:
            operationId: lookup
            summary: Lookup IP Address Geolocation information
            parameters:
                - in: path
                  name: ip
                  required: true
            responses:
                "200":
                    description: OK
                "400":
                    description: Bad Request
                "404":
                    description: Not Found
