openapi: 3.0.0

info:
    title: Lesson 2 lookup harry potter houses
    description: Lesson 2 - Basic request to IP lookup API.
    version: "0.2.2"

servers:
    - url: https://wizard-world-api.herokuapp.com/

paths:
    /houses:
        get:
            operationId: gethouses
            summary: Retrieve all Harry Potter houses
            responses:
                "200":
                description: Success
    /wizards:
        get:
            operationId: getwizards
            summary: Retrieve Harry Potter wizards
            parameters:
                - name: FirstName
                in: query
                required: true
            responses:
                "200":
                description: Success